export const LOGIN = 'LOGIN';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_SEND_EMAIL_VERIFICATION_IS_LOADING =
  'SET_SEND_EMAIL_VERIFICATION_IS_LOADING';
export const SET_SEND_EMAIL_VERIFICATION_STATUS =
  'SET_SEND_EMAIL_VERIFICATION_STATUS';
